always warn about missed daemon scripts

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -230,7 +230,11 @@ ck_daemon() {
 
 # Check if $1 is a valid daemon name
 have_daemon() {
-	[[ -f /etc/rc.d/$1 && -x /etc/rc.d/$1 ]]
+	if [[ ! -f /etc/rc.d/$1 || ! -x /etc/rc.d/$1 ]]; then
+		printf "error: /etc/rc.d/$1 does not exist or is not executable\n" >&2
+		return 1
+	fi
+	return 0
 }
 
 # Check if $1 is started at boot
